<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\KnowledgeVault.Core\KnowledgeVault.Core.csproj" />
    <ProjectReference Include="..\KnowledgeVault.Application\KnowledgeVault.Application.csproj" />
    <ProjectReference Include="..\KnowledgeVault.Infrastructure\KnowledgeVault.Infrastructure.csproj" />
  </ItemGroup>
</Project>
